version: '3'
services:
    pg-test:
        image: 'postgres:latest'
        ports:
            - '5434:5432'
        environment:
            POSTGRES_DB: 'test'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
